BASE_URL="https://tobeto.com"
FORGOT_PASSWORD_URL="https://tobeto.com/sifremi-unuttum"
LOGIN_TOBETO_XLSX="data/loginTobeto.xlsx"
LOGIN_BUTTON_XPATH="//*[@id='offcanvasExample']/div[2]/div[2]/div/a[1]"
LOGIN_BUTTON_CLICK_XPATH="//*[@id='__next']/div/main/section/div/div/div[1]/div/form/button"
E_MAIL= "email"
PASSWORD_NAME = "password"
DOLDURULMASI_ZORUNLU_ALAN= "//p[contains(.,'Doldurulması zorunlu alan*')]"
DOLDURULMASI_ZORUNLU_ALAN_KONTROL= "DOLDURULMASI_ZORUNLU_ALAN"
KAYIT_OL= "//*[@id='__next']/div/section[1]/nav/div/div/a[2]"
NEW_EMAIL="email"
FIRST_NAME="firsName"
LAST_NAME="lastName"
SIFRE="password"
SIFRE_TEKRAR="passwordAgain"
FORGOT_PASSWORD="xpath=//div[@id='__next']/div/main/section/div/div/div/input"

